import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\prsht.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\mshtml.idl";
import "c:\program files\microsoft visual studio .net 2003\vc7\platformsdk\include\dimm.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\mshtmhst.idl";
import "c:\program files\microsoft visual studio .net 2003\vc7\platformsdk\include\docobj.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\exdisp.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\objsafe.idl";

[
	object,
	uuid(078FA70F-278A-4028-ADA4-3C2D8B733A7F),
	dual,
	helpstring("Ixpublisher Interface"),
	pointer_default(unique)
] 
#line 18 "c:\\source\\dimdimcodebase\\v4.1\\components\\cpp\\publisher\\xdimdimcontrol_40\\xpublisher.h"
interface Ixpublisher : IDispatch {
#line 20 "c:\\source\\dimdimcodebase\\v4.1\\components\\cpp\\publisher\\xdimdimcontrol_40\\xpublisher.h"
	[id(1),helpstring("method getProperty")] HRESULT  getProperty([in] BSTR args, [out,retval] BSTR *buf );
	[id(2),helpstring("method getVersion")] HRESULT  getVersion([out,retval] LONG *retval);
	[id(3),helpstring("method performAction")] HRESULT  performAction([in] BSTR args, [out,retval] LONG *retval);
	[id(4),helpstring("method setProperty")] HRESULT  setProperty([in] BSTR args, [out,retval] LONG *retval);
};


[ version(1.0), uuid(51865837-4F59-45EF-AB53-DE0FF9CC5687), helpstring("xDimdimControl_40 1.0 Type Library") ]
library xDimdimControl_40
{
	importlib("stdole2.tlb");
	importlib("olepro32.dll");

	[
		uuid(A1E3BC92-F828-4820-8832-4377621768F7),
		helpstring("_IxpublisherEvents Interface")
	] 
#line 34 "c:\\source\\dimdimcodebase\\v4.1\\components\\cpp\\publisher\\xdimdimcontrol_40\\xpublisher.h"
	dispinterface _IxpublisherEvents {
	properties:

	methods:
	};

	[
		version(1.0),
		uuid(5100F713-1B48-4A6B-9985-EDDFB7F1C0DF),
		helpstring("xpublisher Class")
	] 
#line 49 "c:\\source\\dimdimcodebase\\v4.1\\components\\cpp\\publisher\\xdimdimcontrol_40\\xpublisher.h"
	coclass Cxpublisher {
		interface Ixpublisher;
		[default, source]	interface _IxpublisherEvents;
	};

}

